src/skippy.c
=> Fix flickers when pseudoTrans=false

src/clientwin.c, src/skippy.c
=> Fix multi-monitor pseudoTrans=false bugs

src/layout.c
Gonna test a bit before merging
=> Fix expose boxy rotation contraction collision detection bug

skippy-xd.sample.rc, src/clientwin.c, src/mainwin.c, src/mainwin.h, src/skippy.c, src/skippy.h
=> Keyboard actions similar to mouse actions

src/wm.c
Follows https://specifications.freedesktop.org/wm-spec/1.5/ar01s05.html
=> fitlers out _NET_WM_WINDOW_TYPE_POPUP_MENU

src/skippy.c
=> Add log for paging virtual desktops and screens

src/clientwin.c, src/tooltip.c
Closing #115 
Thanks @ArijanJ for introducing me to the tool rr, without which it would be impossible to debug this.
=> Seamless xrandr reconfiguration

src/skippy.c
=> Pivoting keys for RHS of keyboard

src/skippy.c
=> Add UID to named pipe

src/mainwin.c, src/skippy.c, src/skippy.h
=> Tooltip refresh after reloading

src/skippy.c
=> Fix paging offset when system/pseudoTrans=true and panel/reserveSpace=true

src/skippy.c
Closing #176 
I found only this silly solution, by introduce intermediate virtual desktop switch when paging starting from an empty desktop back to itself.
This solution fails when there is only one virtual desktop and it's empty.
I tidied the code by the way.
=> Introduce intermediate virtual desktop switch

src/skippy.c
=> Clear repeated MapNotify/UnmapNotify events

src/skippy.c
by listening to ConfigureNotify XEvent
=> Keep track of window resizing etc events

skippy-xd.sample.rc, src/clientwin.h, src/layout.c, src/layout.h, src/skippy.c, src/skippy.h
=> Cosmos layout

src/clientwin.c, src/clientwin.h, src/skippy.c
Unsubscribe from events, and move code from clientwin_move() (many calls within animation) to clientwin_premove() (only one call within animation).
=> Performance improvements, RISKY

src/skippy.c, src/skippy.h
=> Config option in conjunction with skippy-xd activation

src/skippy.c
=> Verbosity in client when changing config path

skippy-xd.sample.rc, src/config.c, src/skippy.c, src/skippy.h
Closing #187 
#49 
@ArijanJ hope you are happy with this one?
=> Daemon-to-client pipe and stdout printing

src/skippy.c
=> Remove optimization

src/skippy.c
=> Correct UnmapNotify event number offset

src/skippy.c
An admittedly inelegant solution to send packets to all clients.
The daemon would send the correct number of packets to the same daemon-to-client pipe, and all clients would poll() the same pipe. If they are not able to read from the pipe, they would try again...
Very inelegant solution, but according to my testing it works. The advantage is there is only one daemon-to-client pipe. A clean pipe implementation might involve one pipe per client.
=> Daemon sends packet to all clients

Makefile, meson.build, meson.options
Basic meson build script.  All features should be enabled.  Let me know if making them optional is needed or if I forgot something.  Closes #199
Basic usage:
```
meson setup build [source]
meson compile -C build
meson install -C build --destdir [destination]
```
=> Add meson build system

src/layout.c
=> Catch nan error when collapse speed==0

src/clientwin.c
=> Do not apply tint or rounding to panel/desktop windows

src/skippy.c
- Daemon-client pipe postfixed with client pid
- Client pass pid to daemon
- If client did trigger activation, daemon returns to client when activation completes
- If client did not trigger activation, daemon returns to client immediately
=> Daemon-client pipe implementation proper

src/wm.c
Hi @musqz I created this example PR for #273, which is a code change that you proposed and tested to be working :)
This is to me a good PR that others can work with easily:
- The PR is specific to one bug/task: #273
- The PR links to #273
- Only a few lines are changed (of course that is not always possible)
- The white space and indentation is correct, so that the diff shows clearly the actual lines that are changed
- For this small code change, it is wrapped in one commit
- The commit and PR titles are self explanatory
All these allow me as well as other developers, and even yourself, to keep track of all the code changes, for the purpose of testing, comments, code inspection in the future for bug fixing or other purpose, yeah?
I would love if you can create a PR for this, at your …
=> Use res_class and res_name for window class matching
