felixfung/skippy-xd

src/skippy.c
src/skippy.h

closes #25 
Originally I thought to code the switch feature so that during switchWaitDuration, the user can cycle through the windows without the window previews showing. However I changed my mind, and the user can only switch between current and next/prev window during switchWaitDuration. The reason is because cycling through windows require major refactoring around relevant code paths, as well as maneuver around the windows z-order list, which is susceptible to potential race condition (when windows are created/destroyed/switched with other apps). Not worth all these complications in my opinion.

Honour switchWaitDuration, also refactor switch focus logic

---

skippy-xd.sample.rc
src/mainwin.c
src/mainwin.h
src/skippy.c
src/skippy.h

Pivot keys for expose and paging, refactor --next --prev to cmdline interface
With these changes, the user can configure expose and paging to be used just like Alt-Tab. E.g. Super_L + Tab for `expose --next`, Control_L + Tab for `paging --next`, hit Tab to cycle through cycles/desktop, release Control_L to select. Similar settings can be done for `expose --prev` and `paging --prev`.
When --prev and --next cmdline parameters are not set, then expose and paging becomes toggle (old behaviour) (switch would do nothing).
The user can set pivot keys for expose and paging to be empty, and keep the hot keys without --next or --prev parameters, to use expose and paging with toggle behaviour.

Pivot keys for expose and paging, refactor --next --prev to cmdline interface

---

src/skippy.c

Fixes skippy crashing if it doesn't find a default fillSpec value in the user config, the default string looked like `orig mid mid mid mid #333333`, causing all the parsing functions to get confused.

Fix broken default for fillSpec

---

src/skippy.c
src/skippy.h

For boxy expose, stabilize window layout when z-order changes,

---

src/skippy.c

The new approach is by setting `pending_damage = true` in when desktopwin_map() is invoked.
Very happy about this one :)

Eliminate paging force refresh and minimize CPU cycles

---

src/skippy.c
src/skippy.h

This reverts commit 9dc18db9989fa18c00dabec683313ae1fe5e7d0d.
mw->clientondesktop stores the list of windows in the z-order provided by X11/WM. When we sort this list, we lose/mess up the original z-order.

Revert "For boxy expose, stabilize window layout when z-order changes,"

---

src/layout.c
src/skippy.h

Achieved by sorting window list before layout_boxy()

For boxy expose, stabilize window layout when z-order changes

---

skippy-xd.sample.rc
src/clientwin.c
src/skippy.c
src/tooltip.c

It used to segfault specifically when tooltip/show was false, then set to true via `--config-reload`

Reload config option tooltip/show no longer segfaults

---

src/clientwin.c
src/mainwin.c
src/skippy.c

close #98 
The X events are processed in a non-deterministic series:
In typical sequence, clientwin_handle() is called in
https://github.com/felixfung/skippy-xd/blob/592b26bebafe992517f630f6a2b441fdc889f8f3/src/skippy.c#L1309 which deletes the client window object; then `mw->client_to_focus = NULL` is reset in https://github.com/felixfung/skippy-xd/blob/592b26bebafe992517f630f6a2b441fdc889f8f3/src/skippy.c#L1245 and https://github.com/felixfung/skippy-xd/blob/592b26bebafe992517f630f6a2b441fdc889f8f3/src/skippy.c#L1280 is called, which short circuits on `mw->client_to_focus == NULL`
Sometimes, `mw->client_to_focus = NULL` from https://github.com/felixfung/skippy-xd/blob/592b26bebafe992517f630f6a2b441fdc889f8f3/src/skippy.c#L1245
is NOT called. Then we get dereferencing of the stale pointer …

Fix segfault when long pressing window close

---

src/mainwin.c

The root cause fix for #99 should be to set
```
mw->client_to_focus = NULL;
```

Allow activation when no windows present

---

src/skippy.c

E.g. hold Super to trigger expose, and when Super is released, expose deactivates. In essence it is Alt-Tab without the Tab, using up/down/left/right/prev/next and mouse to navigate.

Pivot key can be single activate key to skippy-xd while holding it

---

src/skippy.c

Just by listening to CreateNotify events, we have thumbnails all the time.
However, nondeterministic segfault after xrandr reconfiguration still exists.
#115

Take CreateNotify and DestroyNotify X events

---

src/skippy.c

The `--config` option is redesigned.
- When used with `--start-daemon` option, the daemon reads in the path
- When `skippy-xd --config config_path` is launched, it tells the daemon to reload the config path. All other options are ignored
- When simply launched with `skippy-xd` with no other options, simple expose mode is triggered

Config file can now reload with new path

---

skippy-xd.sample.rc
src/skippy.c
src/skippy.h
src/wm.c

Closing #13 
Basic usage is 
```
skippy-xd --expose --window-class xterm
```
Basic rule of c regex allows e.g.
```
skippy-xd --expose --window-class xt
```
to filter for xterm

Cmdline option to filter window class

---

README.md
skippy-xd.sample.rc
src/mainwin.c
src/mainwin.h
src/skippy.c
src/skippy.h
src/wm.c

This is a big PR with one commit with the intention of following:
Recent work has revamped the pipe protocol, extending each client-to-server command from single byte to allow for multiple bytes. This allowed loading config file in a new path, as well as window class filtering.
With this protocol change, I realized I could change the current pivot key specification from the config file to the command-line parameter. In other words, the pivot key would not be specified in these configs:
```
keysPivotSwitch = Alt_L
keysPivotExpose = 
keysPivotPaging = 
```
Rather, the user would specify the pivot key in the command line parameter like so:
```
skippy-xd --switch --pivot Alt_L --next
```
There are pros and cons with these two interfaces:
Pivot key location | Example command | Pros | Cons
--- …

Revamp pipe protocol and pivot key interface

---

src/skippy.c

I am in the process of packaging this application for Fedora. I have created a Fedora Copr repository at https://copr.fedorainfracloud.org/coprs/ledif/skippy-xd/package/skippy-xd, which is similar in spirit to the AUR for Fedora.
There are currently two buffer overruns that cause aborts, which seem to only be exposed when building this in a strict environment such as Fedora's infrastructure. Included in this PR is a small set of changes to fix these bugs:
- In `load_config_file()`, the string buffer length does not properly include the size for the first digit of the uid/xid.
- In `send_string_command_to_daemon_via_fifo()`, the string buffer length does not properly include the size for the first character

fix: buffer overrun while writing to fifo

---

src/skippy.c
src/wm.c

PR #181 fixed two buffer overflow errors. After that fix, @nPHYN1T3 and I have been experiencing non-deterministic error:
The client side app would send non-zero length pipe command, but the daemon side app would claim to have received zero length pipe command, hence exiting.
When the relevant fix from #181 is reverted, the error goes away (for me). My guess is that #181 somehow exposes a non-deterministic error in my environment, going from a negligibly small frequency to a big one (around every 7-10 invocations).
The root cause seem to be how I implemented the pipe reading, where I first read one byte for the command length, and then read the rest of the command. Back when I developed the protocol and communication, I knew writing/reading is a bit wonky.
With this PR, I read the pipe …

Fix non-deterministic stubbed command received error

---

src/skippy.c

Fixing the pipe "stubbed command received" error 100%.
I have previously gotten the `<` and `>` mixed up, my bad.
Verified with code inspection, printf, and running the client in an infinite while loop.

Root cause fix pipe stubbed command error

---

src/layout.c

Before expose, first sort by window ID, then by window position

Maintain expose constancy given the same window positions

---

skippy-xd.sample.rc
src/skippy.c

Previously, switch can only focus on next window until live preview pops up (controlled by config option `layout/switchWaitDuration`.
This PR enables cycling through all windows before live preview pops up.
In addition, when the `layout/switchWaitDuration = 0`, live preview never pops up for switch.
This is a pretty complex PR that introduces special cases on switch, changes to important code paths, and potentially messes up Z-order.
This PR needs to be tested carefully before merging.

Switch cycles/focuses windows before live preview

---

src/skippy.c

e.g. `skippy-xd --expose --wm-class XTerm --wm-class firefox` would display both XTerm and firefox windows

Using --wm-class on the same command combines the entries

---

skippy-xd.sample.rc
src/skippy.c
src/skippy.h

Move config option `enforceFocus` from `system` to `bindings`.
I think `bindings` is more appropriate because this option controls whether the keyboard input goes to skippy-xd.
In addition, this config option can be reloaded with `skippy-xd config-reload`.
After this move, all config options in `system` actually require restarting skippy-xd.

Config option system/enforceFocus -> bindings/enforceFocus

---

src/clientwin.c
src/mainwin.c
src/skippy.c
src/tooltip.c
src/wm.c

Window title change:
Fullscreen window: "skippy-xd main window" -> "skippy-xd fullscreen window"
Preview windows: "mini window of 0xXXXX" -> "skippy-xd preview window 0xXXXX"
Paging windows: "[virtual desktop name]" -> "skippy-xd page [virtual desktop name]"
Label windows: "skippy-xd tooltip" -> "skippy-xd label"
The window class is always "skippy-xd"

Rename skippy-xd window titles

---

src/clientwin.c
src/mainwin.c
src/mainwin.h
src/skippy.c

This is likely the best solution:
Select/cancel on key/mouse release.
Originally (not written by me) there were booleans to indicate key or mouse is pressed. I don't think they were actually used.
Of course, these two booleans are updated in event driven manner, through KeyPress event, without polling.
We can poll at 60 Hz for key/mouse release event *only* when skippy-xd is activated, and key/mouse is pressed, indicated by the booleans.
(Of course we also pll at 60 Hz for pivot mode, that is always the case).
This limits polling to minimum, perhaps theoretical minimum.

Select/cancel on key release, no lag, no polling

---

src/clientwin.c
src/clientwin.h
src/mainwin.c
src/skippy.c
src/skippy.h

The root cause of the bug on #339 is that when detecting whether a window is showing on a xinerama screen, the window coordinate before normalization is used.
The lifecycle of a window coordinate is raw window coordinates, then apply layout algorithm, after which window coordinates change. Depending on the layout algorithm, the window coordinates may become bigger than the screen width/height. Subsequent functions performs "normalization", so that window coordinates shrink to within the screen width/height.
Hence, the fix is to call the window coordinate normalization code before this check.
Also tidy up relevant code.

Showonlycurrentmonitor

---

src/clientwin.c
src/clientwin.h

#346 was wrong diagnosis and wrong fix for #339 :P
The root cause of the bug on showOnlyCurrentMonitor is that the windows original coordinates, in the case of paging, is already offset by the virtual desktop the window is sitting on, vs the current one.
Hence, with showOnlyCurrentMonitor = true, the check on the coordinates between window coordinates and xinerama screen coordinates are wrong.
Introduce a set of coordinates per window to store the coordinates before the virtual desktop offset.

Fix showOnlyCurrentMonitor by introducing cw->src0
